# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ptt_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loc.proto',
  package='ptt.loc',
  serialized_pb=_b('\n\tloc.proto\x12\x07ptt.loc\x1a\tptt.proto\"W\n\tLocReport\x12\x0b\n\x03uid\x18\x01 \x02(\x04\x12 \n\tlocations\x18\x02 \x03(\x0b\x32\r.ptt.Location\x12\x1b\n\x04time\x18\x03 \x01(\x0b\x32\r.ptt.DateTime\"1\n\nLocReports\x12#\n\x07reports\x18\x01 \x03(\x0b\x32\x12.ptt.loc.LocReportB\x18\n\x16\x63om.shanlitech.ptt.loc')
  ,
  dependencies=[ptt_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOCREPORT = _descriptor.Descriptor(
  name='LocReport',
  full_name='ptt.loc.LocReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ptt.loc.LocReport.uid', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='locations', full_name='ptt.loc.LocReport.locations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ptt.loc.LocReport.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=120,
)


_LOCREPORTS = _descriptor.Descriptor(
  name='LocReports',
  full_name='ptt.loc.LocReports',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reports', full_name='ptt.loc.LocReports.reports', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=171,
)

_LOCREPORT.fields_by_name['locations'].message_type = ptt_pb2._LOCATION
_LOCREPORT.fields_by_name['time'].message_type = ptt_pb2._DATETIME
_LOCREPORTS.fields_by_name['reports'].message_type = _LOCREPORT
DESCRIPTOR.message_types_by_name['LocReport'] = _LOCREPORT
DESCRIPTOR.message_types_by_name['LocReports'] = _LOCREPORTS

LocReport = _reflection.GeneratedProtocolMessageType('LocReport', (_message.Message,), dict(
  DESCRIPTOR = _LOCREPORT,
  __module__ = 'loc_pb2'
  # @@protoc_insertion_point(class_scope:ptt.loc.LocReport)
  ))
_sym_db.RegisterMessage(LocReport)

LocReports = _reflection.GeneratedProtocolMessageType('LocReports', (_message.Message,), dict(
  DESCRIPTOR = _LOCREPORTS,
  __module__ = 'loc_pb2'
  # @@protoc_insertion_point(class_scope:ptt.loc.LocReports)
  ))
_sym_db.RegisterMessage(LocReports)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.shanlitech.ptt.loc'))
# @@protoc_insertion_point(module_scope)
